#!/bin/bash
set -e
source ${SEMVER_BUMP_LIB}

NEW_VERSION=$(bump $1)
echo "Bumped version from '${CURRENT_VERSION}' to '${NEW_VERSION}'."
echo "Updating version file with '${NEW_VERSION}'."
echo ${NEW_VERSION} > ${VERSION_FILE}
git add ${VERSION_FILE} && git commit -m "${TAG_MESSAGE} ${NEW_VERSION}"
echo "Tagging current commit '$(git rev-parse --short HEAD)' with 'v${NEW_VERSION}'."
git tag -a "v${NEW_VERSION}" -m "${TAG_MESSAGE} ${NEW_VERSION}"
